# You have to rename this file to botconfig (botconfig.toml)

# Bot token
own_bot_token = ""

# message marker
marker = "--"

# channels fot the bot to communicate on
# ex. channel_ids = [717108559525293147, 754320391173827756]
channel_ids = []

# role ids to be added upon acceptin rules
#ex. default_roles = [431853093815189514, 431593983605604372]
default_roles = []
